name: close resolved issues when no response
on:
  workflow_dispatch:
  schedule:
    - cron: "05 7 * * *"

permissions:
  contents: read
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been resolved for 1 day with no activity. Remove stale label or comment or this will be closed in 1 day.'
          close-issue-message: 'This issue was closed because it has been stale for 1 day with no activity.'
          days-before-stale: 1
          days-before-close: 1
          days-before-pr-close: -1
          only-labels: 'resolved'
